# Generated by Django 5.1.3 on 2025-01-08 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_complaintmodel_userinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserInfoModel',
        ),
        migrations.RemoveField(
            model_name='complaintmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='complaintmodel',
            name='isvideo',
        ),
        migrations.RemoveField(
            model_name='complaintmodel',
            name='video',
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='media_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='complaintmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaintmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
