# Generated by Django 5.1.3 on 2025-01-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dislike_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaintmodel',
            unique_together={('subject', 'location')},
        ),
        migrations.RemoveField(
            model_name='complaintmodel',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='complaintmodel',
            name='likes',
        ),
    ]
