# Generated by Django 5.1.3 on 2025-01-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_complaintmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
